Repository boostcampwm-2024/refactor-web18-inear, pull requests merged in 2025-01, with the labels that each got.

#1 앨범 도메인 API 최적화
  server/src/album/album.redis.repository.ts
  server/src/album/album.service.ts
  server/test/load/http-test.yml
  server/test/load/socket-test.yml
Labels: 🚀 Refactor, 🌭 BE

#2 폴더 정리
  client/src/app/router/Layout.tsx
  client/src/app/router/routes.tsx
  client/src/entities/albumCard/index.ts
  client/src/entities/albumCard/model/types.ts
  client/src/entities/albumCard/ui/AlbumCard.tsx
  client/src/entities/albumDetail/types.ts
  client/src/entities/message/types.ts
  client/src/features/commentInput/ui/CommentInput.tsx
  client/src/main.tsx
  client/src/pages/AlbumPage/ui/AlbumPage.tsx
  client/src/pages/MainPage/ui/MainPage.tsx
  client/src/widgets/albumList/index.ts
  client/src/widgets/albumList/ui/AlbumList.tsx
  client/src/widgets/albums/index.ts
  client/src/widgets/albums/ui/AlbumArtist.tsx
  client/src/widgets/albums/ui/Comment.tsx
  client/src/widgets/albums/ui/Playlist.tsx
  client/src/widgets/albums/ui/TrackItem.tsx
Labels: 🍙 FE

#4 시나리오 기반 부하테스트 적용
  package.json
  server/package.json
  server/test/load/http-test.yml
  server/test/load/processor.js
  server/test/load/socket-test.yml
Labels: 🚀 Refactor

#3 소켓 redis adapter 적용
  package.json
  server/src/common/redis-adapter/redis-io.adapter.spec.ts
  server/src/common/redis-adapter/redis-io.adapter.ts
  server/src/main.ts
  server/test/mock/room-gateway.mock.ts
  yarn.lock
Labels: 🚀 Refactor, 🌭 BE
